# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
- main: ./cli/.
  env:
  - CGO_ENABLED=0
  goos:
    - darwin
    - linux
    - freebsd
    - netbsd
    - openbsd
  goarch:
      - amd64
archive:
  replacements:
    darwin: MacOS
    linux: Linux
    windows: Windows
    freebsd: FreeBSD
    netbsd: NetBSD
    openbsd: OpenBSD
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
