language: go
go:
  - 1.13.x
  - tip

services:
  - docker

stages:
  - build
  - name: docker
    if: tag IS present

jobs:
  include:
    - stage: build
      script:
        - go mod vendor
        - go build -o s3sync ./cli
    - stage: docker
      script:
        - docker build -t larrabee/s3sync:${TRAVIS_TAG} .
        - docker login -u "${DOCKERHUB_USER}" -p "${DOCKERHUB_TOKEN}"
        - docker push larrabee/s3sync:${TRAVIS_TAG}
